export const projects = [
  {
    title: 'Moodex',
    type: { en: 'iOS App', zh: 'iOS App' },
    description: {
      en: 'An AI-powered space for capturing thoughts, tracking moods, and finding patterns in everyday life.',
      zh: '一款用于记录想法、追踪情绪并发现日常模式的 AI 工具。',
    },
    highlight: { en: 'Personal knowledge × emotional awareness', zh: '个人知识 × 情绪觉察' },
    visual: { en: 'INNER STATE', zh: '内在状态' },
    href: 'https://moodex.cc',
  },
  {
    title: 'MyVault',
    type: { en: 'iOS App', zh: 'iOS App' },
    description: {
      en: 'A real-world asset manager for documenting what you own and preserving the stories behind it.',
      zh: '一款用于管理真实资产、留存物品故事的应用。',
    },
    highlight: { en: 'Real-world assets × personal stories', zh: '真实资产 × 个人故事' },
    preview: '/myvault-preview.webp',
    href: 'https://myvault.moodex.cc',
  },
  {
    title: 'CircleCast',
    type: { en: 'Podcast', zh: '播客' },
    description: {
      en: 'A podcast and companion app for listening to, recording, and revisiting personal stories.',
      zh: '一档探索个人故事的播客，以及用于引导记录故事的配套应用。',
    },
    highlight: { en: 'Long-form stories × guided reflection', zh: '长篇故事 × 引导回望' },
    visual: { en: 'STORIES', zh: '故事' },
    href: 'https://podcasts.apple.com/cn/podcast/circlecast/id1859906660',
  },
  {
    title: 'Adaptive Eta',
    type: { en: 'AI Agent Skill', zh: 'AI Agent 技能' },
    description: {
      en: 'A task-specific OpenClaw skill for making agent execution more reliable and efficient.',
      zh: '一项面向 OpenClaw 的任务型技能，用于提升智能体执行的可靠性与效率。',
    },
    highlight: { en: 'Agent workflows × practical execution', zh: '智能体工作流 × 实用执行' },
    visual: { en: 'ADAPT', zh: '自适应' },
    href: 'https://clawhub.ai/yanghe1941/adaptive-eta',
  },
];

export const writing = [
  {
    title: { en: 'MyVault: Less Is More', zh: 'MyVault：少即是多，开启极简生活方式' },
    date: '2026-05-28',
    href: 'https://blog.yanghe.moodex.cc/p/myvault-less-is-more-unlock-minimalist-lifestyle',
  },
  {
    title: { en: 'Sleep Anxiety and Rebuilding a Productive Life', zh: '随手记001｜失眠、猝死焦虑与生产力重建' },
    date: '2026-04-03',
    href: 'https://blog.yanghe.moodex.cc/p/sleep-anxiety-productive-lifestyle-recovery',
  },
  {
    title: { en: 'A New Exploration: CircleCast', zh: '我的新探索，CircleCast 播客，开搞' },
    date: '2025-12-01',
    href: 'https://blog.yanghe.moodex.cc/p/my-new-exploration-circlecast-podcast-start',
  },
];

export const experiences = [
  {
    date: { en: '2023 - Present', zh: '2023 至今' },
    company: { en: 'Personal Projects', zh: 'Personal Projects' },
    position: { en: 'Independent Developer & AI Explorer', zh: '独立开发者 & AI 探索者' },
    content: {
      en: 'Dedicated to bringing technology into everyday life. Built iOS apps including Moodex and MyVault.',
      zh: '致力于将技术融入生活。开发了 Moodex、MyVault 等多款 iOS 应用。',
    },
  },
  {
    date: { en: '2023 - Present', zh: '2023 - 至今' },
    company: { en: 'Damus Lab', zh: 'Damus Lab' },
    position: { en: 'Co-founder', zh: '联合创始人' },
    content: {
      en: 'Based overseas long term, working on brand and e-commerce operations in Indonesia.',
      zh: '长期 base 海外，负责印尼区域品牌、电商等业务。',
    },
  },
  {
    date: { en: '2021 - 2022', zh: '2021 - 2022' },
    company: { en: 'WOOK', zh: 'WOOK' },
    companyHref: 'https://home.wook.cn/id',
    position: { en: 'Brand Operations Manager', zh: '品牌运营经理' },
    content: {
      en: 'Contributed to brand growth and operating system improvements.',
      zh: '参与品牌增长与运营体系建设。',
    },
  },
  {
    date: { en: '2020 - 2021', zh: '2020 - 2021' },
    company: { en: 'WeGene', zh: 'WeGene 微基因' },
    companyHref: 'https://www.wegene.com/en/',
    position: { en: 'Operations Manager', zh: '运营经理' },
    content: {
      en: 'Responsible for e-commerce operations and user growth for consumer genetic testing products.',
      zh: '负责消费级基因检测产品的电商运营与用户增长。',
    },
  },
  {
    date: { en: '2019 - 2020', zh: '2019 - 2020' },
    company: { en: 'MOTI', zh: 'MOTI 魔笛' },
    companyHref: 'https://motiplanet.com/',
    position: { en: 'Domestic Market User Growth', zh: 'MOTI 国内市场用户增长' },
    content: {
      en: 'Supported domestic market user growth.',
      zh: '负责国内市场用户增长。',
    },
  },
  {
    date: { en: '2017 - 2018', zh: '2017 - 2018' },
    company: { en: 'Elephant Club', zh: '大象公会' },
    companyHref: 'https://zh.wikipedia.org/zh-cn/%E5%A4%A7%E8%B1%A1%E5%85%AC%E4%BC%9A',
    position: { en: 'Business Manager', zh: '商务经理' },
    content: {
      en: 'Handled business affairs for Elephant Club, StoryFM, and Paperclip projects.',
      zh: '大象公会、故事FM、回形针项目的商务事宜。',
    },
  },
  {
    date: { en: '2013 - 2017', zh: '2013 - 2017' },
    company: { en: 'Hebei University of Technology', zh: '河北工业大学' },
    position: { en: '—', zh: '—' },
  },
];

export const navItems = [
  { href: '#about', key: 'about' },
  { href: '#projects', key: 'projects' },
  { href: '#writing', key: 'writing' },
  { href: '#experience', key: 'experience' },
  { href: '#contact', key: 'contact' },
];

export const siteCopy = {
  en: {
    title: 'Yanghe | Portfolio',
    description: 'Yanghe is an independent developer building thoughtful AI products, personal tools, and market research.',
    nav: {
      about: 'About',
      projects: 'Projects',
      writing: 'Writing',
      experience: 'Experience',
      contact: 'Contact',
    },
    blog: 'Blog',
    heroEyebrow: 'Portfolio',
    heroName: 'Independent developer building calm, useful AI products.',
    heroLead: 'I design personal tools that bring more clarity to everyday life.',
    heroBody: 'My work spans product design, AI workflows, and writing about markets, technology, and life.',
    heroPrimary: 'Explore projects',
    heroSecondary: 'Start a conversation',
    focusLabel: 'Focus',
    focusTitle: 'Product / AI / Market research',
    focusPoints: ['Designing for clarity, hierarchy, and fast reading.', 'Exploring the overlap between products and everyday life.'],
    projectsKicker: 'Projects',
    projectsTitle: 'Selected projects',
    projectLink: 'Explore project',
    writingKicker: 'Writing',
    writingTitle: 'Ideas in progress',
    writingDescription: 'Notes on building products, paying attention, and making sense of change.',
    writingLink: 'Read all writing',
    experienceKicker: 'Experience',
    experienceTitle: 'Career timeline',
    table: {
      date: 'Date',
      company: 'Company',
      position: 'Role',
      content: 'Details',
    },
    contactKicker: 'Contact',
    contactTitle: 'Have a product idea, story, or collaboration in mind?',
    contactBody: 'I am open to thoughtful conversations about products, AI, brands, and life overseas.',
    contactButton: 'Email Yanghe',
    footer: '© {year} Yanghe. All rights reserved.',
    languageToggle: '中文',
    languageToggleLabel: 'Switch to Chinese',
    a11y: {
      skipToContent: 'Skip to content',
      openMenu: 'Open menu',
      closeMenu: 'Close menu',
      primaryNav: 'Primary',
      mobileNav: 'Mobile',
      backToTop: 'Back to top',
      email: 'Email',
      appPreview: '{title} app preview',
    },
  },
  zh: {
    title: '杨鹤 | Portfolio',
    description: '杨鹤是一名独立开发者，构建有温度的 AI 产品、个人工具，并持续进行市场与生活方式研究。',
    nav: {
      about: '关于',
      projects: '项目',
      writing: '写作',
      experience: '经历',
      contact: '联系方式',
    },
    blog: '博客',
    heroEyebrow: '作品集',
    heroName: '构建平静、好用的 AI 个人产品。',
    heroLead: '我设计帮助人们更清晰地记录、理解与整理日常生活的工具。',
    heroBody: '工作横跨产品设计、AI 工作流，也分享市场、技术与生活方式相关的思考。',
    heroPrimary: '浏览项目',
    heroSecondary: '开始交流',
    focusLabel: '重点',
    focusTitle: '产品 / AI / 市场研究',
    focusPoints: ['注重信息层级与阅读效率。', '关注产品与生活方式的结合点。'],
    projectsKicker: '项目',
    projectsTitle: '精选项目',
    projectLink: '查看项目',
    writingKicker: '写作',
    writingTitle: '正在形成的想法',
    writingDescription: '关于做产品、保持观察，以及理解变化的记录。',
    writingLink: '阅读全部文章',
    experienceKicker: '经历',
    experienceTitle: '职业经历',
    table: {
      date: '日期',
      company: '公司',
      position: '职位',
      content: '内容',
    },
    contactKicker: '联系',
    contactTitle: '有产品想法、故事或合作想聊？',
    contactBody: '欢迎交流产品、AI、品牌与海外生活相关的话题。',
    contactButton: '邮件联系杨鹤',
    footer: '© {year} 杨鹤 版权所有',
    languageToggle: 'EN',
    languageToggleLabel: '切换到英文',
    a11y: {
      skipToContent: '跳到正文',
      openMenu: '打开菜单',
      closeMenu: '关闭菜单',
      primaryNav: '主导航',
      mobileNav: '移动端导航',
      backToTop: '回到顶部',
      email: '邮箱',
      appPreview: '{title} 应用预览',
    },
  },
};
